projects:
  tarttest:
    schemaPath: graphql/schema.json
    includes:
      - graphQL
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: .
